[package]
name = "lib-hello"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Having dual function two return value as a condition"
authors = ["WhatADumb"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
